app/models/admin.rb
config/routes.rb
db/migrate/20200816090038_devise_create_admins.rb
db/schema.rb
test/fixtures/admins.yml
test/models/admin_test.rb

DeviseでAdminのデータ型のマイグレーション完了しました。

[devise]Adminマイグレーション

---

app/assets/javascripts/customer/cart_items.coffee
app/assets/stylesheets/customer/cart_items.scss
app/controllers/customer/cart_items_controller.rb
app/helpers/customer/cart_items_helper.rb
app/models/cart_item.rb
db/migrate/20200816112751_create_cart_items.rb
db/schema.rb
test/controllers/customer/cart_items_controller_test.rb
test/fixtures/cart_items.yml
test/models/cart_item_test.rb

Customer cart items モデル、コントローラー追加

---

app/assets/javascripts/customer/cart_items.coffee
app/assets/javascripts/customer/homes.coffee
app/assets/stylesheets/customer/cart_items.scss
app/assets/stylesheets/customer/homes.scss
app/controllers/customer/cart_items_controller.rb
app/controllers/customer/homes_controller.rb
app/helpers/customer/cart_items_helper.rb
app/helpers/customer/homes_helper.rb
app/models/cart_item.rb
db/migrate/20200816112751_create_cart_items.rb
db/schema.rb
test/controllers/customer/cart_items_controller_test.rb
test/controllers/customer/homes_controller_test.rb
test/fixtures/cart_items.yml
test/models/cart_item_test.rb

Customer homes コントローラ追加しました。
確認お願いします。

Customer homes コントローラ追加

---

app/assets/javascripts/admin/orders.coffee
app/assets/stylesheets/admin/orders.scss
app/controllers/admin/orders_controller.rb
app/helpers/admin/orders_helper.rb
app/models/order.rb
db/migrate/20200816123417_create_orders.rb
db/schema.rb
test/controllers/admin/orders_controller_test.rb
test/fixtures/orders.yml
test/models/order_test.rb

[Admin-orders]model, contoroller追加しました。
確認お願いいたします。

[Admin-orders]model, contoroller

---

app/assets/javascripts/admin/genres.coffee
app/assets/stylesheets/admin/genres.scss
app/controllers/admin/genres_controller.rb
app/helpers/admin/genres_helper.rb
test/controllers/admin/genres_controller_test.rb

ジャンルのコントローラーを作成しました。
確認お願いします。

ジgenres controller sakusei

---

app/assets/javascripts/customer/addresses.coffee
app/assets/stylesheets/customer/addresses.scss
app/controllers/customer/addresses_controller.rb
app/helpers/customer/addresses_helper.rb
app/models/address.rb
db/migrate/20200817030503_create_addresses.rb
db/schema.rb
test/controllers/customer/addresses_controller_test.rb
test/fixtures/addresses.yml
test/models/address_test.rb

addressesモデルを作成しました！
確認お願いします！

Install addresses

---

app/controllers/admin/homes_controller.rb
app/views/admin/homes/top.html.erb
config/routes.rb

[Admin-homes]view, controller 追加しました。
確認お願いします。

[Admin-homes]view, controller 追加

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/customers/confirmations/new.html.erb
app/views/customers/mailer/confirmation_instructions.html.erb
app/views/customers/mailer/email_changed.html.erb
app/views/customers/mailer/password_change.html.erb
app/views/customers/mailer/reset_password_instructions.html.erb
app/views/customers/mailer/unlock_instructions.html.erb
app/views/customers/passwords/edit.html.erb
app/views/customers/passwords/new.html.erb
app/views/customers/registrations/edit.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
app/views/customers/shared/_error_messages.html.erb
app/views/customers/shared/_links.html.erb
app/views/customers/unlocks/new.html.erb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/layouts/application.html.erb
config/initializers/kaminari_config.rb
config/routes.rb

①下記gemfile追加しました。Bootstrapは動作確認済みです。
- refile
- refile-mini_magick
- bootstrap-sass
- kaminari
②基本となりそうなルーティングを記載しました。（config/route.rb）
③その他僕の担当部分の作業が入っちゃっているかもしれないんですが、それは無視してもらって大丈夫です。

Gemと基本のルーティング追加

---

app/controllers/admin/customers_controller.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/index.html.erb
app/views/admin/customers/show.html.erb
app/views/admins/sessions/new.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
app/views/customers/shared/_links.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/schema.rb
db/seeds.rb

- 退会アクション問題なさそうです。
- db/seeds に追加して15人分会員作成されるようにしました。（マージされたら $rails db:seed をやる必要あります。）
- 新規登録、ログイン画面など見やすくしました
- 試しにAdmin側の会員一覧ページにページング追加してみました。
- devise のデフォルトでAdminのURLが/adminsになっていたので、route.rbの中で/adminに修正

退会アクション、ユーザ関連レイアウト修正など

---

app/controllers/admin/genres_controller.rb
app/models/genre.rb
app/views/admin/genres/index.html.erb

モデルにvalidatesの追加、コントローラーにbefore_actionの追加、ビューのレイアウトを少し変えました！
確認お願いします！

reiauto tuika

---

app/controllers/customers/passwords_controller.rb
app/controllers/customers/registrations_controller.rb
app/views/admins/sessions/new.html.erb
app/views/customer/customers/show.html.erb
app/views/customers/passwords/new.html.erb
app/views/customers/registrations/edit.html.erb
app/views/customers/registrations/new.html.erb
config/routes.rb

下記のページ追加しました。
- ログインできなかった時のパスワード再発行ページ（会員ログイン画面からアクセス）
- ログイン後のパスワード変更ページ（マイページからアクセス）

Customer customer

---

app/controllers/admin/orders_controller.rb

[admin-controller]updated

---

app/controllers/admin/genres_controller.rb
app/models/genre.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
db/seeds.rb

モデルのnameの部分がnemeになっていたため修正しました！
確認お願いします！

moderu hennsyuu

---

app/assets/stylesheets/application.scss
app/controllers/admin/customers_controller.rb
app/controllers/customer/customers_controller.rb
app/models/customer.rb
app/models/genre.rb
app/views/admin/customers/edit.html.erb
app/views/admins/sessions/new.html.erb
app/views/customer/customers/edit.html.erb
app/views/customers/sessions/new.html.erb
config/locales/devise.ja.yml

下記のページで日本語のエラーメッセージが表示されるよう編集しました。
- 会員新規登録ページ
- 会員ログインページ
- 会員登録情報編集ページ 
- 管理者ログインページ
- 管理者会員情報編集ページ

ユーザー関連日本語エラーメッセージ表示

---

app/assets/javascripts/admin/search.coffee
app/assets/javascripts/customer/search.coffee
app/assets/stylesheets/admin/search.scss
app/assets/stylesheets/customer/search.scss
app/controllers/admin/search_controller.rb
app/controllers/customer/search_controller.rb
app/helpers/admin/search_helper.rb
app/helpers/customer/search_helper.rb
app/views/admin/customers/_index.html.erb
app/views/admin/customers/index.html.erb
app/views/admin/search/search.html.erb
app/views/customer/search/search.html.erb
app/views/layouts/application.html.erb
config/routes.rb
test/controllers/admin/search_controller_test.rb
test/controllers/customer/search_controller_test.rb

検索機能追加してみました。おかしいとこあれば教えてください。
会員側：商品（商品名対応）検索
管理者側：会員（メールアドレス対応）・商品（商品名対応）検索

商品または会員検索機能追加

---

app/controllers/customer/cart_items_controller.rb
app/helpers/application_helper.rb
app/views/customer/cart_items/index.html.erb

エラー1：別のユーザーのアイテムがカートに入っている
ユーザーごとにカートアイテムの個数が切り替わるよう修正しました。
エラー２: カートの中の個数が表示されない
表示されるようになりました。

Customer cart items修正

---

app/views/customer/cart_items/index.html.erb

Cart-items修正しました。
確認おねがいいたします。

Customer cart items更新

---

app/controllers/admin/genres_controller.rb
app/models/genre.rb

フラッシュメッセージを追加し、モデルの部分をhas_manyへ変更しました！
確認お願いします！

flash-message tuika

---

app/controllers/admin/search_controller.rb
app/controllers/customer/search_controller.rb
app/views/admin/search/search.html.erb
app/views/admins/sessions/new.html.erb
app/views/customer/items/show.html.erb
app/views/layouts/_search.html.erb

- 検索機能の表示アップデートしました。
（Admin側の会員検索機能はレイアウト難しそうなので消しました。）
- 商品個数選択の表示アップデートしました。

検索機能アップデート

---

app/controllers/admin/customers_controller.rb
app/controllers/admin/homes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/order_details_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/admin/search_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/customer/orders_controller.rb
app/views/admin/items/new.html.erb

- テストも並行して進めて行きたいので、コントローラのbefore_actionを復活させました。
- Adminの商品登録のセレクト部分のレイアウト整えました。

before_action and item new

---

app/controllers/customer/homes_controller.rb
app/controllers/customer/items_controller.rb
app/controllers/customer/search_controller.rb
app/views/admin/items/new.html.erb
app/views/customer/items/_index.html.erb
app/views/layouts/_genre_search.html.erb

商品を多数追加した際にCustomerの商品一覧2ページ以降で不具合があったので修正しました。

ページングの不具合修正

---

app/views/customer/homes/top.html.erb
app/views/customer/items/_index.html.erb

商品画像から商品詳細画面に遷移できるようにしました！
確認お願いします！

Recommended

---

app/controllers/application_controller.rb
app/controllers/customer/customers_controller.rb
app/controllers/customers/sessions_controller.rb
app/models/customer.rb
app/views/customers/sessions/new.html.erb

- 会員は退会後にトップページに遷移され、その後ログインできないように修正
- 管理者ログアウト後に、管理者ログインページに遷移するよう修正

[修正]　退会機能と管理者ログアウト時の遷移先

---

app/assets/stylesheets/application.scss
app/views/customer/addresses/index.html.erb
app/views/customer/customers/edit.html.erb
app/views/customer/customers/show.html.erb
app/views/customer/items/index.html.erb
app/views/customer/items/show.html.erb
app/views/customer/search/search.html.erb
app/views/customers/registrations/edit.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb

細々した修正と、
customer/addresses/index.html.erbで登録先がない場合、
「現在登録の配送先はありません」と表示されるよう修正させていただきますした！

customer 側Layout修正

---

app/controllers/admin/order_details_controller.rb
app/controllers/admin/orders_controller.rb
app/views/admin/orders/show.html.erb
app/views/layouts/_header.html.erb

admin orderにエラーがあったので修正しました。
確認おねがいします。

[admin-order]修正

---

app/views/customer/addresses/edit.html.erb

会員側マイページのレイアウト修正しました。
確認おねがいします。

[layout]Updated customer-mypage

---

app/views/admin/items/edit.html.erb
app/views/admin/items/show.html.erb
app/views/admins/sessions/new.html.erb

itemのedit部分が修正できていたなかったので直しました。

[layout]修正

---

app/assets/stylesheets/application.scss
app/views/admins/sessions/new.html.erb
app/views/customer/customers/edit.html.erb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb

[layout]modified
